name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          ./build-pkg.sh cabot_site_test_room
          ./build-pkg.sh cabot_site_large_room

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./pkg/cabot_site_test_room.zip,./pkg/cabot_site_large_room.zip
